### ISSUE TITLE
如何上传aar pom中所包含的dependency定义的lib

### ISSUE THREAD

**Issue by carl1990** [YuTianTina/ForMultiUploadMaven#2]
我现在在打包的时候需要像别的应用一样将该aar 所依赖的其他的aar也一块上传，这样方便在使用的时候只依赖朱包就好了 可以自动下载相应依赖，该怎么做啊。虽然pom中定义了dependency但是相应的包并没有上传啊

**Comment by YuTianTina** [comment]
指定对应的configuration就可以做到,
artifacts{
                archives 指定你要上传的目标aar文件地址
            }

**Comment by YuTianTina** [comment]
> 我现在在打包的时候需要像别的应用一样将该aar 所依赖的其他的aar也一块上传，这样方便在使用的时候只依赖朱包就好了 可以自动下载相应依赖，该怎么做啊。虽然pom中定义了dependency但是相应的包并没有上传啊

指定对应的configuration就可以做到,
artifacts{
archives 指定你要上传的目标aar文件地址
}
