### ISSUE TITLE
无法成功打包aar

### ISSUE THREAD

**Issue by monakatyking** [YuTianTina/ForMultiUploadMaven#3]
17:54:03: Executing task 'publish'...

Executing tasks: [publish]

Configuration on demand is an incubating feature.

> Configure project :mylibrary
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to D:\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

WARNING: API 'variantOutput.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Task :mylibrary:preBuild UP-TO-DATE
> Task :mylibrary:preFullReleaseBuild UP-TO-DATE
> Task :mylibrary:compileFullReleaseAidl NO-SOURCE
> Task :mylibrary:compileFullReleaseRenderscript
> Task :mylibrary:checkFullReleaseManifest
> Task :mylibrary:generateFullReleaseBuildConfig
> Task :mylibrary:generateFullReleaseResValues
> Task :mylibrary:generateFullReleaseResources
> Task :mylibrary:packageFullReleaseResources
> Task :mylibrary:processFullReleaseManifest
> Task :mylibrary:generateFullReleaseRFile
> Task :mylibrary:prepareLintJar UP-TO-DATE
> Task :mylibrary:generateFullReleaseSources
> Task :mylibrary:javaPreCompileFullRelease
> Task :mylibrary:compileFullReleaseJavaWithJavac
> Task :mylibrary:extractFullReleaseAnnotations
> Task :mylibrary:mergeFullReleaseConsumerProguardFiles UP-TO-DATE
> Task :mylibrary:mergeFullReleaseShaders
> Task :mylibrary:compileFullReleaseShaders
> Task :mylibrary:generateFullReleaseAssets
> Task :mylibrary:packageFullReleaseAssets
> Task :mylibrary:packageFullReleaseRenderscript NO-SOURCE
> Task :mylibrary:processFullReleaseJavaRes NO-SOURCE
> Task :mylibrary:transformResourcesWithMergeJavaResForFullRelease
> Task :mylibrary:transformClassesAndResourcesWithSyncLibJarsForFullRelease
> Task :mylibrary:compileFullReleaseNdk NO-SOURCE
> Task :mylibrary:mergeFullReleaseJniLibFolders
> Task :mylibrary:transformNativeLibsWithMergeJniLibsForFullRelease
> Task :mylibrary:transformNativeLibsWithSyncJniLibsForFullRelease
> Task :mylibrary:bundleFullReleaseAar
> Task :mylibrary:compileFullReleaseSources
> Task :mylibrary:mergeFullReleaseResources
> Task :mylibrary:verifyFullReleaseResources
> Task :mylibrary:assembleFullRelease
> Task :mylibrary:fullReleaseJavadoc NO-SOURCE
> Task :mylibrary:fullReleaseJavadocJar
> Task :mylibrary:preFullDebugBuild UP-TO-DATE
> Task :mylibrary:compileFullDebugAidl NO-SOURCE
> Task :mylibrary:compileFullDebugRenderscript UP-TO-DATE
> Task :mylibrary:checkFullDebugManifest UP-TO-DATE
> Task :mylibrary:generateFullDebugBuildConfig UP-TO-DATE
> Task :mylibrary:generateFullDebugResValues
> Task :mylibrary:generateFullDebugResources
> Task :mylibrary:packageFullDebugResources
> Task :mylibrary:processFullDebugManifest
> Task :mylibrary:generateFullDebugRFile
> Task :mylibrary:generateFullDebugSources UP-TO-DATE
> Task :mylibrary:javaPreCompileFullDebug
> Task :mylibrary:compileFullDebugJavaWithJavac
> Task :mylibrary:extractFullDebugAnnotations
> Task :mylibrary:mergeFullDebugConsumerProguardFiles UP-TO-DATE
> Task :mylibrary:mergeFullDebugShaders
> Task :mylibrary:compileFullDebugShaders
> Task :mylibrary:generateFullDebugAssets
> Task :mylibrary:packageFullDebugAssets
> Task :mylibrary:packageFullDebugRenderscript NO-SOURCE
> Task :mylibrary:processFullDebugJavaRes NO-SOURCE
> Task :mylibrary:transformResourcesWithMergeJavaResForFullDebug
> Task :mylibrary:transformClassesAndResourcesWithSyncLibJarsForFullDebug
> Task :mylibrary:compileFullDebugNdk NO-SOURCE
> Task :mylibrary:mergeFullDebugJniLibFolders
> Task :mylibrary:transformNativeLibsWithMergeJniLibsForFullDebug
> Task :mylibrary:transformNativeLibsWithSyncJniLibsForFullDebug
> Task :mylibrary:bundleFullDebugAar
> Task :mylibrary:compileFullDebugSources
> Task :mylibrary:assembleFullDebug
> Task :mylibrary:preSimpleDebugBuild UP-TO-DATE
> Task :mylibrary:compileSimpleDebugAidl NO-SOURCE
> Task :mylibrary:compileSimpleDebugRenderscript
> Task :mylibrary:checkSimpleDebugManifest
> Task :mylibrary:generateSimpleDebugBuildConfig
> Task :mylibrary:generateSimpleDebugResValues
> Task :mylibrary:generateSimpleDebugResources
> Task :mylibrary:packageSimpleDebugResources
> Task :mylibrary:processSimpleDebugManifest
> Task :mylibrary:generateSimpleDebugRFile
> Task :mylibrary:generateSimpleDebugSources
> Task :mylibrary:javaPreCompileSimpleDebug
> Task :mylibrary:compileSimpleDebugJavaWithJavac
> Task :mylibrary:extractSimpleDebugAnnotations
> Task :mylibrary:mergeSimpleDebugConsumerProguardFiles UP-TO-DATE
> Task :mylibrary:mergeSimpleDebugShaders
> Task :mylibrary:compileSimpleDebugShaders
> Task :mylibrary:generateSimpleDebugAssets
> Task :mylibrary:packageSimpleDebugAssets
> Task :mylibrary:packageSimpleDebugRenderscript NO-SOURCE
> Task :mylibrary:processSimpleDebugJavaRes NO-SOURCE
> Task :mylibrary:transformResourcesWithMergeJavaResForSimpleDebug
> Task :mylibrary:transformClassesAndResourcesWithSyncLibJarsForSimpleDebug
> Task :mylibrary:compileSimpleDebugNdk NO-SOURCE
> Task :mylibrary:mergeSimpleDebugJniLibFolders
> Task :mylibrary:transformNativeLibsWithMergeJniLibsForSimpleDebug
> Task :mylibrary:transformNativeLibsWithSyncJniLibsForSimpleDebug
> Task :mylibrary:bundleSimpleDebugAar
> Task :mylibrary:compileSimpleDebugSources
> Task :mylibrary:assembleSimpleDebug
> Task :mylibrary:assembleDebug
> Task :mylibrary:assembleFull
> Task :mylibrary:preSimpleReleaseBuild UP-TO-DATE
> Task :mylibrary:compileSimpleReleaseAidl NO-SOURCE
> Task :mylibrary:compileSimpleReleaseRenderscript
> Task :mylibrary:checkSimpleReleaseManifest
> Task :mylibrary:generateSimpleReleaseBuildConfig
> Task :mylibrary:generateSimpleReleaseResValues
> Task :mylibrary:generateSimpleReleaseResources
> Task :mylibrary:packageSimpleReleaseResources
> Task :mylibrary:processSimpleReleaseManifest
> Task :mylibrary:generateSimpleReleaseRFile
> Task :mylibrary:generateSimpleReleaseSources
> Task :mylibrary:javaPreCompileSimpleRelease
> Task :mylibrary:compileSimpleReleaseJavaWithJavac
> Task :mylibrary:extractSimpleReleaseAnnotations
> Task :mylibrary:mergeSimpleReleaseConsumerProguardFiles UP-TO-DATE
> Task :mylibrary:mergeSimpleReleaseShaders
> Task :mylibrary:compileSimpleReleaseShaders
> Task :mylibrary:generateSimpleReleaseAssets
> Task :mylibrary:packageSimpleReleaseAssets
> Task :mylibrary:packageSimpleReleaseRenderscript NO-SOURCE
> Task :mylibrary:processSimpleReleaseJavaRes NO-SOURCE
> Task :mylibrary:transformResourcesWithMergeJavaResForSimpleRelease
> Task :mylibrary:transformClassesAndResourcesWithSyncLibJarsForSimpleRelease
> Task :mylibrary:compileSimpleReleaseNdk NO-SOURCE
> Task :mylibrary:mergeSimpleReleaseJniLibFolders
> Task :mylibrary:transformNativeLibsWithMergeJniLibsForSimpleRelease
> Task :mylibrary:transformNativeLibsWithSyncJniLibsForSimpleRelease
> Task :mylibrary:bundleSimpleReleaseAar
> Task :mylibrary:compileSimpleReleaseSources
> Task :mylibrary:mergeSimpleReleaseResources
> Task :mylibrary:verifySimpleReleaseResources
> Task :mylibrary:assembleSimpleRelease
> Task :mylibrary:assembleRelease
> Task :mylibrary:assembleSimple
> Task :mylibrary:assemble

> Task :mylibrary:lint
Ran lint on variant simpleDebug: 3 issues found
Ran lint on variant fullRelease: 3 issues found
Ran lint on variant fullDebug: 3 issues found
Ran lint on variant simpleRelease: 3 issues found
Wrote HTML report to file:///E:/ForMultiUploadMaven-master/mylibrary/build/reports/lint-results.html
Wrote XML report to file:///E:/ForMultiUploadMaven-master/mylibrary/build/reports/lint-results.xml

> Task :mylibrary:generateFullDebugUnitTestSources UP-TO-DATE
> Task :mylibrary:preFullDebugUnitTestBuild UP-TO-DATE
> Task :mylibrary:javaPreCompileFullDebugUnitTest
> Task :mylibrary:compileFullDebugUnitTestJavaWithJavac
> Task :mylibrary:processFullDebugUnitTestJavaRes NO-SOURCE
> Task :mylibrary:transformClassesAndResourcesWithPrepareIntermediateJarsForFullDebug
> Task :mylibrary:testFullDebugUnitTest
> Task :mylibrary:generateFullReleaseUnitTestSources UP-TO-DATE
> Task :mylibrary:preFullReleaseUnitTestBuild UP-TO-DATE
> Task :mylibrary:javaPreCompileFullReleaseUnitTest
> Task :mylibrary:compileFullReleaseUnitTestJavaWithJavac
> Task :mylibrary:processFullReleaseUnitTestJavaRes NO-SOURCE
> Task :mylibrary:transformClassesAndResourcesWithPrepareIntermediateJarsForFullRelease
> Task :mylibrary:testFullReleaseUnitTest
> Task :mylibrary:generateSimpleDebugUnitTestSources UP-TO-DATE
> Task :mylibrary:preSimpleDebugUnitTestBuild UP-TO-DATE
> Task :mylibrary:javaPreCompileSimpleDebugUnitTest
> Task :mylibrary:compileSimpleDebugUnitTestJavaWithJavac
> Task :mylibrary:processSimpleDebugUnitTestJavaRes NO-SOURCE
> Task :mylibrary:transformClassesAndResourcesWithPrepareIntermediateJarsForSimpleDebug
> Task :mylibrary:testSimpleDebugUnitTest
> Task :mylibrary:generateSimpleReleaseUnitTestSources UP-TO-DATE
> Task :mylibrary:preSimpleReleaseUnitTestBuild UP-TO-DATE
> Task :mylibrary:javaPreCompileSimpleReleaseUnitTest
> Task :mylibrary:compileSimpleReleaseUnitTestJavaWithJavac
> Task :mylibrary:processSimpleReleaseUnitTestJavaRes NO-SOURCE
> Task :mylibrary:transformClassesAndResourcesWithPrepareIntermediateJarsForSimpleRelease
> Task :mylibrary:testSimpleReleaseUnitTest
> Task :mylibrary:test
> Task :mylibrary:check
> Task :mylibrary:build
> Task :mylibrary:fullReleaseSymbolJar
> Task :mylibrary:generatePomFileForFullReleasePublication
> Task :mylibrary:publishFullReleasePublicationToMavenRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mylibrary:publishFullReleasePublicationToMavenRepository'.
> Failed to publish publication 'FullRelease' to repository 'maven'
   > Authentication scheme 'all'(Authentication) is not supported by protocol 'file'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 19s
106 actionable tasks: 98 executed, 8 up-to-date
17:54:23: Task execution finished 'publish'.

**Comment by YuTianTina** [comment]
you can unset NDK in your AS
[please see this sof](https://stackoverflow.com/questions/42682357/how-to-fix-android-studios-2-3-ndk-bug)

<img width="930" alt="WX20190520-102522@2x" src="https://user-images.githubusercontent.com/18045830/57992997-9eb2d700-7ae9-11e9-810d-318b7d4360c8.png">
