### ISSUE TITLE
使用 uploadArchives 並沒有真的包出四種 productFlavor x builtType aar

### ISSUE THREAD

**Issue by toshuyu** [YuTianTina/ForMultiUploadMaven#4]
跑範例程式，使用 README 裡面的 uploadArchives
apply from : "maven_config.gradle"
// apply from: 'maven_variant_config.gradle'

確實可以生出四個組合資料夾
![image](https://raw.githubusercontent.com/YuTianTina/ForMultiUploadMaven/master/assets/demopic.png)
但是實際打開aar檢查，發現裡面都是使用 `defaultPublishConfig 'fullRelease'` 也就是fullRelease 的設定
並非 simpleDebug, simpleRelease, fullDebug, fullRelease 四種組合

**Comment by YuTianTina** [comment]
> 跑範例程式，使用 README 裡面的 uploadArchives
> apply from : "maven_config.gradle"
> // apply from: 'maven_variant_config.gradle'
> 
> 確實可以生出四個組合資料夾
> ![image](https://raw.githubusercontent.com/YuTianTina/ForMultiUploadMaven/master/assets/demopic.png)
> 但是實際打開aar檢查，發現裡面都是使用 `defaultPublishConfig 'fullRelease'` 也就是fullRelease 的設定
> 並非 simpleDebug, simpleRelease, fullDebug, fullRelease 四種組合

可以试下最新代码
