### ISSUE TITLE
没有开始构建

### ISSUE THREAD

**Issue by aitazhixin** [YuTianTina/ForMultiUploadMaven#5]
这是我使用的方式
Flavors是：
    productFlavors {
        hls{
            dimension "default"
        }
        mir{
            dimension "default"
        }
    }

变体配置：
android.libraryVariants.all {
            variant ->
                def isFlavor = !variant.flavorName.isEmpty()
                def _name = "${variant.name}"
                println "variant name $_name"
                println project.archivesBaseName
                addFilter(_name){artifact, file->
                    true
                }
                pom(_name).groupId = "com.mydemo.test"
                pom(_name).artifactId = _name + "test" // 项目名称（通常为类库模块名称，也可以任意）
                pom(_name).version = "1.0.0-SNAPSHOT" // 版本号
    }
}

但是构建Task没有执行就success，有遇到相似情况吗？

**Comment by YuTianTina** [comment]
你这样只是新增了配置pom, artifacts仍然是默认的release的编译
